version: "3.8"

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Ensure this aligns with OpenShift's routing
    environment:
      - FLASK_ENV=production
      # Add any additional environment variables needed for OpenShift
